server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true


#server:
#  port: 9090
#
#spring:
#  jpa:
#    database: mysql
#    hibernate:
#      ddl-auto: create
#    database-platform:
#  datasource:
#    url: jdbc:mysql://bj-cynosdbmysql-grp-og8zp5ro.sql.tencentcdb.com:26956/software_testing
#    name: movie_share
#    password: Movie123456
#    username: movie_share

