server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:./test
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true


