server:
  port: 8081

spring:

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

  application:
    name: order-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
